# Set working directory
setwd("~/Desktop")
maindir <- getwd()
datadir <- file.path("~/Desktop/")

# Load packages
library("readxl")
library("ggplot2")
library("ggpubr")
library("reshape2")
library("emmeans")
library("hrbrthemes")
library("umx")
library("interactions")
library("car")

# Import data
data_ppi <- read_excel("~/Documents/Documents_Air/Github/istart-socdoors/derivatives/palm_data/data_deception-exclusions/ppi_domain_x_outcome.xlsx")
design_contrast <- read_excel("~/Documents/Documents_Air/Github/istart-socdoors/derivatives/palm_data/design_contrast.xlsx")
data_act <- read_excel("~/Documents/Documents_Air/Github/istart-socdoors/derivatives/palm_data/data/act_outcome.xlsx")
design_average <- read_excel("~/Documents/Documents_Air/Github/istart-socdoors/derivatives/palm_data/design_average.xlsx")
socialdoors_model2 <- read_excel("~/Documents/Documents_Air/Github/istart-socdoors/derivatives/imaging_plots/istart_covariates_socialdoors_2.xlsx")

# **Fig. 3. Aberrant reward sensitivity blunts the relationship between substance use and striatal activation during receipt of #rewards**
# Activation, Outcome, c12: SU*RS_sq-neg
model1 <- lm(data_act$VS ~
               design_average$tsnr_avg + design_average$fd_mean_avg + design_average$RS + design_average$RS_square + design_average$SU + design_average$SUxRS + design_average$SUxRS_sq)
summary(model1)

# scatter plot dividing by aberrant vs moderate RS (i.e., positive RS_sq vs negative)
scatter <- ggplot(design_average, aes(x=RS_linear, y=VS, col=SubstanceUse))+
  geom_point()+
  geom_point(shape=1,color="black")+
  geom_smooth(method=lm, formula= y ~ poly(x,2), level=0.99, se=FALSE, fullrange=TRUE, linetype="dashed")+ #formula= y ~ x+I(x^2)
  scale_x_continuous(breaks = seq(-6, 6, by = 2))

# remove gridlines
scatter + scale_color_grey() + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
                                     panel.background = element_blank(), axis.line = element_line(colour = "black"))
# https://r-graph-gallery.com/ggplot2-color.html



#**Figure 4. Substance use is associated with blunted TPJ responses to social vs. monetary reward**
# Cluster tstat 8 (SU-neg) TPJ
model1 <- lm(aug22_task_socialdoors_model_2_type_act_cnum_4_thresh_clustere_corrp_tstat8 ~
               tsnr + fd_mean + RS + RS_square + SU + SUxRS + SUxRS_sq, data=socialdoors_model2)
summary(model1)

# Partial Residual Plot
crModel <- crPlots(model1, 
                   smooth=FALSE, 
                   pch=21,
                   col="yellow",
                   bg="yellow",
                   col.lines="black",
                   lwd=1,
                   grid=FALSE
)

#**Fig. 5. Substance use is associated with decreased VS-dmPFC connectivity for social vs. monetary reward**
# ppi_VS-dmPFC, domain * outcome, c8: SU-neg
model1 <- lm(data_ppi$dmPFC ~
               design_contrast$tsnr + design_contrast$fd_mean + design_contrast$RS + design_contrast$RS_square + design_contrast$SU + design_contrast$SUxRS + design_contrast$SUxRS_sq)
summary(model1)
# Partial Residual Plot
crModel <- crPlots(model1, 
                   smooth=FALSE, 
                   col="pink", 
                   bg="pink",
                   col.lines="black",
                   pch=21,
                   lwd=1,
                   grid=FALSE
)

#**Fig. 6. Reward sensitivity is associated with increased VS-vmPFC connectivity for social vs. monetary reward**
# ppi_VS-vmPFC, domain * outcome, c3: RS-pos
model1 <- lm(data_ppi$vmPFC ~
               design_contrast$tsnr + design_contrast$fd_mean + design_contrast$RS + design_contrast$RS_square + design_contrast$SU + design_contrast$SUxRS + design_contrast$SUxRS_sq)
summary(model1)
# Partial Residual Plot
crModel <- crPlots(model1, 
                   smooth=FALSE, 
                   col="orange",
                   bg="orange",
                   col.lines="black",
                   pch=21,
                   lwd=1,
                   grid=FALSE
)
#
#
#
#
#
#
#
# Remove deception subs
data_act <- data_act[!((data_act$sub==1012) | (data_act$sub==1019) | (data_act$sub==1247) | (data_act$sub==1251) | (data_act$sub==1303) | (data_act$sub==3116) | (data_act$sub==3143) | (data_act$sub==3176)), ]

design_average <- design_average[!((design_average$sub==1012) | (design_average$sub==1019) | (design_average$sub==1247) | (design_average$sub==1251) | (design_average$sub==1303) | (design_average$sub==3116) | (design_average$sub==3143) | (design_average$sub==3176)), ]

socialdoors_model2 <- socialdoors_model2[!((socialdoors_model2$sub==1012) | (socialdoors_model2$sub==1019) | (socialdoors_model2$sub==1247) | (socialdoors_model2$sub==1251) | (socialdoors_model2$sub==1303) | (socialdoors_model2$sub==3116) | (socialdoors_model2$sub==3143) | (socialdoors_model2$sub==3176)), ]

data_ppi <- data_ppi[!((data_ppi$sub==1012) | (data_ppi$sub==1019) | (data_ppi$sub==1247) | (data_ppi$sub==1251) | (data_ppi$sub==1303) | (data_ppi$sub==3116) | (data_ppi$sub==3143) | (data_ppi$sub==3176)), ]

design_contrast <- design_contrast[!((design_contrast$sub==1012) | (design_contrast$sub==1019) | (design_contrast$sub==1247) | (design_contrast$sub==1251) | (design_contrast$sub==1303) | (design_contrast$sub==3116) | (design_contrast$sub==3143) | (design_contrast$sub==3176)), ]

# **Fig. 3. Aberrant reward sensitivity blunts the relationship between substance use and striatal activation during receipt of #rewards**
# Activation, Outcome, c12: SU*RS_sq-neg
model1 <- lm(data_act$VS ~
               design_average$tsnr_avg + design_average$fd_mean_avg + design_average$RS + design_average$RS_square + design_average$SU + design_average$SUxRS + design_average$SUxRS_sq)
summary(model1)

# scatter plot dividing by aberrant vs moderate RS (i.e., positive RS_sq vs negative)
scatter <- ggplot(design_average, aes(x=RS_linear, y=VS, col=SubstanceUse))+
  geom_point()+
  geom_point(shape=1,color="black")+
  geom_smooth(method=lm, formula= y ~ poly(x,2), level=0.99, se=FALSE, fullrange=TRUE, linetype="dashed")+ #formula= y ~ x+I(x^2)
  scale_x_continuous(breaks = seq(-6, 6, by = 2))

# remove gridlines
scatter + scale_color_grey() + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
                                     panel.background = element_blank(), axis.line = element_line(colour = "black"))
# https://r-graph-gallery.com/ggplot2-color.html



#**Figure 4. Substance use is associated with blunted TPJ responses to social vs. monetary reward**
# Cluster tstat 8 (SU-neg) TPJ
model1 <- lm(aug22_task_socialdoors_model_2_type_act_cnum_4_thresh_clustere_corrp_tstat8 ~
               tsnr + fd_mean + RS + RS_square + SU + SUxRS + SUxRS_sq, data=socialdoors_model2)
summary(model1)

# Partial Residual Plot
crModel <- crPlots(model1, 
                   smooth=FALSE, 
                   pch=21,
                   col="yellow",
                   bg="yellow",
                   col.lines="black",
                   lwd=1,
                   grid=FALSE
)



#**Fig. 5. Substance use is associated with decreased VS-dmPFC connectivity for social vs. monetary reward**
# ppi_VS-dmPFC, domain * outcome, c8: SU-neg
model1 <- lm(data_ppi$dmPFC ~
               design_contrast$tsnr + design_contrast$fd_mean + design_contrast$RS + design_contrast$RS_square + design_contrast$SU + design_contrast$SUxRS + design_contrast$SUxRS_sq)
summary(model1)
# Partial Residual Plot
crModel <- crPlots(model1, 
                   smooth=FALSE, 
                   col="pink", 
                   bg="pink",
                   col.lines="black",
                   pch=21,
                   lwd=1,
                   grid=FALSE
)



#**Fig. 6. Reward sensitivity is associated with increased VS-vmPFC connectivity for social vs. monetary reward**
# ppi_VS-vmPFC, domain * outcome, c3: RS-pos
model1 <- lm(data_ppi$vmPFC ~
               design_contrast$tsnr + design_contrast$fd_mean + design_contrast$RS + design_contrast$RS_square + design_contrast$SU + design_contrast$SUxRS + design_contrast$SUxRS_sq)
summary(model1)
# Partial Residual Plot
crModel <- crPlots(model1, 
                   smooth=FALSE, 
                   col="orange",
                   bg="orange",
                   col.lines="black",
                   pch=21,
                   lwd=1,
                   grid=FALSE
)
